[build]
  command = "CI= npm run build"
  publish = "build"
  environment = "NODE_ENV=production"

[functions]
  directory = "functions"

[dev]
  port = 5000

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  PORT = "5000"
  API_URL = "/api/v1/"
  JWT_PRIVATE_KEY = "IamShadow"
  JWT_REFRESH_KEY = "Hayabusa"
  MONGODB_URI = "mongodb+srv://IamShadow:IamShadow26@cluster0.nvrqahb.mongodb.net/"
