[build]
  command = "npm run build"
  publish = "build"

[functions]
  directory = "functions"  # Bu yerda sizning serverless funksiyalaringiz bo'ladi

[dev]
  port = 5000  # Development server port

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  PORT = "5000"
  API_URL = "/api/v1/"
  JWT_PRIVATE_KEY = "IamShadow"
  JWT_REFRESH_KEY = "Hayabusa"
  MONGODB_URI = "mongodb+srv://IamShadow:IamShadow26@cluster0.nvrqahb.mongodb.net/"
