[build]
  command = "npm run build"  # Replace with your build command if needed
  publish = "dist"  # Replace with your publish directory if needed

  # Environment variables configuration
  environment = { 
    NODE_ENV = "production",  # Set your Node environment
    MONGODB_URI = "mongodb+srv://IamShadow:IamShadow26@cluster0.nvrqahb.mongodb.net/"  # Replace with your MongoDB URI
  }

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[context.production.environment]
  # Production environment variables
  NODE_ENV = "production"
  MONGODB_URI = "mongodb+srv://IamShadow:IamShadow26@cluster0.nvrqahb.mongodb.net/"

[context.deploy-preview.environment]
  # Deploy preview environment variables
  NODE_ENV = "development"
  MONGODB_URI = "mongodb+srv://IamShadow:IamShadow26@cluster0.nvrqahb.mongodb.net/"

[context.branch-deploy.environment]
  # Branch deploy environment variables
  NODE_ENV = "development"
  MONGODB_URI = "mongodb+srv://IamShadow:IamShadow26@cluster0.nvrqahb.mongodb.net/"

[dev]
  command = "npm run start"  # Replace with your development server start command if needed
