[build]
  command = "npm start"
  publish = "dist"
  timeout = 25  # Increase timeout limit to 25 minutes or higher if necessary
  
[build.environment]
  NODE_ENV = "production"
  MONGODB_URI = "mongodb+srv://IamShadow:IamShadow26@cluster0.nvrqahb.mongodb.net/"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[context.production.environment]
  NODE_ENV = "production"
  MONGODB_URI = "mongodb+srv://IamShadow:IamShadow26@cluster0.nvrqahb.mongodb.net/"

[context.deploy-preview.environment]
  NODE_ENV = "development"
  MONGODB_URI = "mongodb+srv://IamShadow:IamShadow26@cluster0.nvrqahb.mongodb.net/"

[context.branch-deploy.environment]
  NODE_ENV = "development"
  MONGODB_URI = "mongodb+srv://IamShadow:IamShadow26@cluster0.nvrqahb.mongodb.net/"

[dev]
  command = "npm run start"  # Development server start command if needed
