[build]
  command = "CI= npm run build"
  publish = "build"
  environment = "NODE_ENV=production"

[functions]
  directory = "functions"

[dev]
  port = 5000

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
